import type { Agent, AgentCategory, Plan, AgentStatus } from './types'

// ── Helper to build an Agent from compact data ──────────────
function mkAgent(
  id: string, slug: string, name: string, category: AgentCategory,
  tier: 'pro' | 'enterprise', icon: string, description: string,
  capabilities: string[], rating: number, deployCount: number,
  longDescription?: string,
  agentStatus: AgentStatus = 'live',
): Agent {
  const tierMap = { pro: 'PRO' as const, enterprise: 'ENTERPRISE' as const }
  const priceMap = { PRO: { monthly: 4900, annual: 47000 }, ENTERPRISE: { monthly: 49900, annual: 479000 } }
  const mapped = tierMap[tier]
  return {
    id, slug, name, category, tier: mapped, description, longDescription, icon, capabilities, rating, deployCount,
    short_name: name,
    tagline: description,
    active: true,
    agentStatus,
    monthly_price: priceMap[mapped].monthly,
    annual_price: priceMap[mapped].annual,
    one_time_price: 0,
    review_count: Math.floor(deployCount * 0.3),
    usage_count: deployCount,
    featured: rating >= 4.8,
    demo_available: true,
    created_at: '2026-01-01T00:00:00Z',
    branch: category,
    suite: category,
  }
}

// ── 70 San Antonio Agents ────────────────────────────────────
export const SA_AGENTS: Agent[] = [
  // ═══ CIVIC (10) ═══
  mkAgent('civic-001', 'sa-permit-navigator', 'SA Permit Navigator', 'Civic', 'pro', 'FileText',
    'Automates City of San Antonio permit applications, status tracking, and compliance checks.',
    ['Permit status tracking', 'Document preparation', 'Fee calculation', 'Inspector scheduling'],
    4.8, 312,
    'Connects to the City of San Antonio\'s Development Services portal to streamline building permits, zoning requests, and inspection scheduling. Reduces permit processing time from weeks to hours.',
  ),
  mkAgent('civic-002', 'sa-311-dispatcher', 'SA 311 Dispatcher', 'Civic', 'pro', 'PhoneCall',
    'Triages and routes 311 service requests to the correct city department with auto-ticket generation.',
    ['Service request intake', 'Department routing', 'Status notifications', 'Priority scoring'],
    4.6, 189,
    'AI-powered intake agent that handles pothole reports, code violations, noise complaints, and other service requests \u2014 automatically routing them to the right city department and providing citizens with real-time status updates.',
  ),
  mkAgent('civic-003', 'bexar-voter-guide', 'Bexar Voter Guide', 'Civic', 'pro', 'Vote',
    'Nonpartisan election assistant providing ballot info, polling locations, and candidate summaries.',
    ['Ballot lookup', 'Polling locator', 'Registration check', 'Candidate info'],
    4.9, 456,
  ),
  mkAgent('civic-004', 'sa-utilities-concierge', 'SA Utilities Concierge', 'Civic', 'pro', 'Zap',
    'CPS Energy & SAWS billing analysis, outage alerts, and conservation program enrollment.',
    ['Bill analysis', 'Outage alerts', 'Conservation programs', 'Payment plans'],
    4.5, 278,
  ),
  mkAgent('civic-005', 'sa-transit-planner', 'VIA Transit Planner', 'Civic', 'pro', 'Bus',
    'Real-time VIA Metropolitan Transit route planning with accessibility-aware scheduling.',
    ['Route optimization', 'Real-time tracking', 'ADA options', 'Trip alerts'],
    4.3, 201,
  ),
  mkAgent('civic-006', 'sa-parks-events', 'SA Parks & Events', 'Civic', 'pro', 'TreePine',
    'Discover and book San Antonio parks, pavilions, and city-sponsored events.',
    ['Facility booking', 'Event calendar', 'Permit requests', 'Recreation programs'],
    4.4, 134,
  ),
  mkAgent('civic-007', 'sa-code-compliance', 'Code Compliance Advisor', 'Civic', 'pro', 'Shield',
    'Automated code violation detection and remediation guidance for property owners.',
    ['Violation lookup', 'Remediation plans', 'Contractor referrals', 'Appeal assistance'],
    4.2, 89,
  ),
  mkAgent('civic-008', 'sa-library-ai', 'SA Library Research AI', 'Civic', 'pro', 'BookOpen',
    'San Antonio Public Library catalog search, holds management, and research assistance.',
    ['Catalog search', 'Hold management', 'Research assistance', 'E-resource access'],
    4.7, 167,
  ),
  mkAgent('civic-009', 'sa-budget-tracker', 'City Budget Transparency', 'Civic', 'pro', 'PieChart',
    'Natural language queries against the City of San Antonio annual budget and expenditure data.',
    ['Budget queries', 'Expenditure tracking', 'Department comparison', 'Grant monitoring'],
    4.5, 92,
  ),
  mkAgent('civic-010', 'sa-housing-navigator', 'SA Housing Navigator', 'Civic', 'pro', 'Home',
    'Affordable housing program matching, application assistance, and waitlist tracking for Bexar County residents.',
    ['Program matching', 'Application assistance', 'Waitlist tracking', 'Landlord mediation'],
    4.6, 143,
  ),

  // ═══ BUSINESS (10) ═══
  mkAgent('biz-001', 'sa-biz-license-pro', 'SA Business License Pro', 'Business', 'pro', 'Briefcase',
    'End-to-end business licensing, state registration, and ongoing compliance monitoring for San Antonio.',
    ['License applications', 'SOS filings', 'Compliance monitoring', 'Renewal automation'],
    4.7, 384,
    'Automates Texas Secretary of State filings, DBA registration, sales tax permits, and City of San Antonio business licenses \u2014 with renewal reminders and regulatory change monitoring.',
  ),
  mkAgent('biz-002', 'sa-market-intel', 'SA Market Intelligence', 'Business', 'pro', 'TrendingUp',
    'Competitive intelligence and market analysis for San Antonio metro area businesses.',
    ['Competitor analysis', 'Market sizing', 'Demographic trends', 'Foot traffic data'],
    4.5, 219,
  ),
  mkAgent('biz-003', 'sa-hr-compliance', 'TX HR Compliance Guard', 'Business', 'pro', 'Users',
    'Texas labor law compliance monitoring, employee handbook generation, and HR policy automation.',
    ['Policy generation', 'Compliance alerts', 'Handbook builder', 'Audit preparation'],
    4.6, 298,
  ),
  mkAgent('biz-004', 'sa-grant-finder', 'SA Grant & Incentive Finder', 'Business', 'pro', 'DollarSign',
    'Matches SA businesses with federal, state, and city grants, tax incentives, and SAEDF programs.',
    ['Grant matching', 'Application drafting', 'SAEDF navigation', 'Reporting assistance'],
    4.8, 176,
  ),
  mkAgent('biz-005', 'sa-inventory-ai', 'Smart Inventory AI', 'Business', 'pro', 'Package',
    'Demand forecasting and inventory optimization for San Antonio retail and wholesale businesses.',
    ['Demand forecasting', 'Reorder automation', 'Supplier matching', 'Waste reduction'],
    4.4, 134,
  ),
  mkAgent('biz-006', 'sa-social-manager', 'SA Social Media Manager', 'Business', 'pro', 'Share2',
    'AI content generation, scheduling, and analytics tuned to San Antonio culture and audiences.',
    ['Content generation', 'Post scheduling', 'Sentiment analysis', 'Competitor tracking'],
    4.5, 267,
  ),
  mkAgent('biz-007', 'sa-customer-intel', 'Customer Intelligence Suite', 'Business', 'pro', 'LineChart',
    'CRM enrichment, churn prediction, and NPS analysis for San Antonio service businesses.',
    ['Churn prediction', 'CRM enrichment', 'NPS tracking', 'Segmentation'],
    4.3, 98,
  ),
  mkAgent('biz-008', 'sa-legal-assist', 'TX Business Legal Assist', 'Business', 'enterprise', 'Scale',
    'Contract review, NDA drafting, and Texas commercial law guidance \u2014 attorney review required for final docs.',
    ['Contract review', 'NDA drafting', 'Compliance checks', 'Risk flagging'],
    4.7, 89,
  ),
  mkAgent('biz-009', 'sa-tax-prep', 'TX Sales Tax Agent', 'Business', 'pro', 'Receipt',
    'Texas sales & use tax calculation, filing preparation, and audit defense documentation.',
    ['Tax calculation', 'Filing prep', 'Audit defense', 'Nexus analysis'],
    4.6, 201,
  ),
  mkAgent('biz-010', 'sa-real-estate-ai', 'SA Real Estate Intelligence', 'Business', 'pro', 'Building',
    'Commercial and residential property analysis, valuation, and investment underwriting for Bexar County.',
    ['Property valuation', 'Comparable analysis', 'Investment modeling', 'Market forecasting'],
    4.5, 156,
  ),
  mkAgent('biz-011', 'sa-food-truck-compliance', 'Food Truck Compliance Agent', 'Business', 'pro', 'Truck',
    'Guides through Metro Health regulations, FireSafeSA inspections, and parking zone requirements for SA food trucks.',
    ['Health permits', 'Fire inspection prep', 'Parking zones', 'Vendor licensing'],
    4.6, 234,
  ),
  mkAgent('biz-012', 'sa-sbeda-matchmaker', 'SBEDA Procurement Matchmaker', 'Business', 'pro', 'Handshake',
    'Matches minority/women-owned businesses with municipal RFPs and drafts bid templates for City of SA contracts.',
    ['RFP matching', 'Bid drafting', 'Certification guidance', 'Deadline tracking'],
    4.7, 178,
  ),
  mkAgent('biz-013', 'sa-franchise-advisor', 'Franchise Feasibility Advisor', 'Business', 'pro', 'Store',
    'Evaluates franchise opportunities against SA market data, demographics, and competition analysis.',
    ['Market analysis', 'FDD review', 'Territory evaluation', 'ROI projection'],
    4.4, 112,
  ),
  mkAgent('biz-014', 'sa-contractor-verifier', 'Contractor License Verifier', 'Business', 'pro', 'BadgeCheck',
    'Validates contractor licenses, insurance, and bond status for San Antonio commercial projects.',
    ['License lookup', 'Insurance verification', 'Bond status', 'Complaint history'],
    4.5, 145,
  ),
  mkAgent('biz-015', 'sa-export-compliance', 'Export Compliance Navigator', 'Business', 'enterprise', 'Globe',
    'Guides SA manufacturers through export regulations, tariffs, and international trade compliance.',
    ['Export licensing', 'Tariff classification', 'Sanctions screening', 'Documentation'],
    4.3, 89,
  ),
  mkAgent('biz-016', 'sa-startup-funding', 'Startup Funding Navigator', 'Business', 'pro', 'Rocket',
    'Matches early-stage SA startups with angel investors, accelerators, VCs, and grant programs.',
    ['Investor matching', 'Pitch prep', 'Grant identification', 'Accelerator applications'],
    4.8, 198,
  ),
  mkAgent('biz-017', 'sa-commercial-lease', 'Commercial Lease Analyzer', 'Business', 'pro', 'FileSearch',
    'Reviews commercial lease terms, identifies unfavorable clauses, and benchmarks against SA market rates.',
    ['Clause analysis', 'Rate benchmarking', 'Negotiation points', 'Renewal tracking'],
    4.6, 134,
  ),
  mkAgent('biz-018', 'sa-workforce-recruiter', 'SA Workforce Recruiter', 'Business', 'pro', 'UserSearch',
    'Connects SA businesses with qualified local candidates through Workforce Solutions Alamo pipeline.',
    ['Candidate matching', 'Skills assessment', 'Job posting', 'Pipeline tracking'],
    4.5, 167,
  ),
  mkAgent('biz-019', 'sa-biz-insurance', 'Business Insurance Advisor', 'Business', 'pro', 'ShieldCheck',
    'Compares commercial insurance options and identifies coverage gaps for San Antonio businesses.',
    ['Coverage comparison', 'Gap analysis', 'Claims guidance', 'Renewal optimization'],
    4.4, 123,
  ),
  mkAgent('biz-020', 'sa-marketing-campaign', 'SA Marketing Campaign Builder', 'Business', 'pro', 'Megaphone',
    'Creates localized digital marketing campaigns targeting San Antonio demographics and neighborhoods.',
    ['Campaign creation', 'Audience targeting', 'Ad copy generation', 'Performance tracking'],
    4.7, 256,
  ),

  // ═══ MILITARY (10) ═══
  mkAgent('mil-001', 'jbsa-benefits-navigator', 'JBSA Benefits Navigator', 'Military', 'pro', 'Medal',
    'DoD benefits counseling, BAH/BAS calculations, and TRICARE enrollment for Joint Base San Antonio personnel.',
    ['Benefits counseling', 'BAH/BAS calculation', 'TRICARE enrollment', 'VA transition'],
    4.9, 1204,
    'Comprehensive benefits navigation for the 250,000+ military personnel and dependents at JBSA \u2014 covering pay, housing allowances, TRICARE health enrollment, and VA benefit transitions.',
  ),
  mkAgent('mil-002', 'sa-vet-transition', 'SA Veteran Transition Coach', 'Military', 'pro', 'Compass',
    'Career transition coaching, resume translation, and civilian job matching for San Antonio veterans.',
    ['MOS translation', 'Resume building', 'Job matching', 'Certification guidance'],
    4.8, 678,
  ),
  mkAgent('mil-003', 'jbsa-housing-agent', 'JBSA Housing Agent', 'Military', 'pro', 'MapPin',
    'On-post and off-post housing search, BAH-optimized filtering, and PCS move coordination.',
    ['Housing search', 'BAH optimization', 'PCS coordination', 'School lookup'],
    4.7, 892,
  ),
  mkAgent('mil-004', 'sa-gi-bill-advisor', 'GI Bill Education Advisor', 'Military', 'pro', 'GraduationCap',
    'GI Bill benefit optimization, school comparison, and enrollment guidance for SA-area veterans.',
    ['Benefit calculation', 'School comparison', 'Enrollment guidance', 'MHA optimization'],
    4.8, 534,
  ),
  mkAgent('mil-005', 'jbsa-appointment-ai', 'JBSA Appointment Scheduler', 'Military', 'pro', 'Calendar',
    'Medical, dental, and admin appointment scheduling across JBSA facilities with wait time optimization.',
    ['Appointment booking', 'Wait time estimates', 'Referral management', 'Reminder automation'],
    4.6, 445,
  ),
  mkAgent('mil-006', 'sa-ptsd-support', 'SA Veteran Mental Health Navigator', 'Military', 'pro', 'HeartHandshake',
    'Connects veterans and active duty with SA-area mental health resources, crisis lines, and peer support.',
    ['Resource matching', 'Crisis navigation', 'Peer support', 'Appointment access'],
    4.9, 312,
  ),
  mkAgent('mil-007', 'sa-sba-vet-loans', 'Veteran Business Loans Agent', 'Military', 'pro', 'Banknote',
    'SBA veteran loan programs, SBIR/STTR guidance, and small business formation for SA-area vets.',
    ['SBA loan matching', 'Application assistance', 'Business formation', 'Grant identification'],
    4.6, 198,
  ),
  mkAgent('mil-008', 'jbsa-security-clearance', 'Clearance Status Tracker', 'Military', 'enterprise', 'Lock',
    'SF-86 preparation assistance, investigation status tracking, and adjudication guidance (UNCLASSIFIED).',
    ['SF-86 guidance', 'Status tracking', 'Adjudication info', 'PR scheduling'],
    4.7, 234,
  ),
  mkAgent('mil-009', 'sa-mil-spouse-jobs', 'Military Spouse Career Agent', 'Military', 'pro', 'Sparkles',
    'Remote-first job matching, license portability guidance, and entrepreneur resources for military spouses.',
    ['Remote job matching', 'License portability', 'MSEP employer list', 'Certification help'],
    4.7, 289,
  ),
  mkAgent('mil-010', 'sa-vet-claims-ai', 'VA Claims Accelerator', 'Military', 'pro', 'FileCheck',
    'VA disability claim preparation, nexus letter guidance, and DBQ coordination for SA veterans.',
    ['Claim preparation', 'Rating estimation', 'Nexus guidance', 'Appeal support'],
    4.8, 567,
  ),

  // ═══ HEALTHCARE (10) ═══
  mkAgent('hc-001', 'sa-care-navigator', 'SA Care Navigator', 'Healthcare', 'pro', 'Stethoscope',
    'Insurance-aware provider search, appointment booking, and care coordination for San Antonio patients.',
    ['Provider search', 'Cost estimation', 'Appointment booking', 'Referral coordination'],
    4.7, 892,
    'Navigates the complex San Antonio healthcare landscape \u2014 University Health, Baptist, Methodist, Christus \u2014 matching patients to in-network providers, estimating costs, and coordinating referrals.',
  ),
  mkAgent('hc-002', 'sa-rx-optimizer', 'SA Rx Optimizer', 'Healthcare', 'pro', 'Pill',
    'Prescription cost comparison, GoodRx integration, and patient assistance program matching for SA residents.',
    ['Price comparison', 'Coupon finder', 'PAP matching', 'Generic alternatives'],
    4.6, 445,
  ),
  mkAgent('hc-003', 'sa-mental-health-match', 'SA Mental Health Connector', 'Healthcare', 'pro', 'Brain',
    'Therapist and psychiatrist matching with sliding-scale and Medicaid-accepting providers in Bexar County.',
    ['Provider matching', 'Sliding scale search', 'Crisis resources', 'Telehealth options'],
    4.8, 634,
  ),
  mkAgent('hc-004', 'sa-chronic-care', 'Chronic Care Manager', 'Healthcare', 'pro', 'Activity',
    'Diabetes, hypertension, and heart disease management with local specialist coordination and lab tracking.',
    ['Condition monitoring', 'Lab tracking', 'Medication adherence', 'Specialist coordination'],
    4.5, 267,
  ),
  mkAgent('hc-005', 'sa-insurance-navigator', 'Health Insurance Navigator', 'Healthcare', 'pro', 'ShieldCheck',
    'ACA marketplace, CHIP, and Medicaid enrollment guidance for uninsured Bexar County residents.',
    ['Plan comparison', 'Subsidy calculation', 'Enrollment assistance', 'Deadline alerts'],
    4.7, 378,
  ),
  mkAgent('hc-006', 'sa-senior-care', 'SA Senior Care Advisor', 'Healthcare', 'pro', 'Users',
    'Medicare counseling, assisted living search, and caregiver resource coordination for Bexar County seniors.',
    ['Medicare guidance', 'Facility search', 'Caregiver matching', 'Benefits enrollment'],
    4.8, 312,
  ),
  mkAgent('hc-007', 'sa-dental-finder', 'SA Dental Access Agent', 'Healthcare', 'pro', 'SmilePlus',
    'Medicaid and low-cost dental care finder with emergency dental triage for uninsured SA residents.',
    ['Provider search', 'Cost estimation', 'Emergency triage', 'Payment plans'],
    4.5, 189,
  ),
  mkAgent('hc-008', 'sa-maternal-health', 'SA Maternal Health Guide', 'Healthcare', 'pro', 'Baby',
    'Prenatal care coordination, WIC enrollment, and postpartum support navigation for SA mothers.',
    ['Prenatal scheduling', 'WIC enrollment', 'Doula matching', 'Postpartum resources'],
    4.9, 423,
    undefined, 'demo',
  ),
  mkAgent('hc-009', 'sa-clinical-trials', 'SA Clinical Trial Matcher', 'Healthcare', 'pro', 'FlaskConical',
    'Matches San Antonio patients to active clinical trials at UT Health SA, UTHSC, and Methodist Research.',
    ['Trial matching', 'Eligibility screening', 'Enrollment support', 'Progress tracking'],
    4.6, 134,
    undefined, 'demo',
  ),
  mkAgent('hc-010', 'sa-hospital-bills', 'Medical Bill Negotiator', 'Healthcare', 'pro', 'Receipt',
    'Audits hospital bills for errors, identifies charity care eligibility, and negotiates balances for SA patients.',
    ['Bill auditing', 'Error detection', 'Charity care', 'Negotiation scripts'],
    4.7, 198,
    undefined, 'demo',
  ),

  // ═══ TOURISM (10) ═══
  mkAgent('tour-001', 'sa-riverwalk-concierge', 'Riverwalk Concierge', 'Tourism', 'pro', 'Waves',
    'Personalized restaurant, entertainment, and attraction recommendations along the San Antonio River Walk.',
    ['Restaurant booking', 'Event tickets', 'Tour scheduling', 'Accessibility info'],
    4.9, 2341,
    'Your AI guide to the 15-mile River Walk \u2014 restaurant reservations, event tickets, seasonal festivals, boat tour scheduling, and accessibility information for the full experience.',
  ),
  mkAgent('tour-002', 'sa-alamo-guide', 'Alamo & Missions Guide', 'Tourism', 'pro', 'Landmark',
    'Interactive AI guide to the Alamo, Mission San Jos\u00e9, and all five World Heritage missions.',
    ['Historical narration', 'Tour scheduling', 'Ticket booking', 'Accessibility info'],
    4.8, 1876,
  ),
  mkAgent('tour-003', 'sa-hotel-optimizer', 'SA Hotel Price Optimizer', 'Tourism', 'pro', 'Bed',
    'Real-time hotel price tracking and booking optimization across San Antonio properties.',
    ['Price comparison', 'Deal alerts', 'Booking assistance', 'Loyalty optimization'],
    4.6, 987,
  ),
  mkAgent('tour-004', 'sa-fiesta-planner', 'Fiesta & Events Planner', 'Tourism', 'pro', 'PartyPopper',
    'Complete planning guide for Fiesta San Antonio, rodeo, and year-round cultural events.',
    ['Event calendar', 'Ticket booking', 'Parade routes', 'Hotel recommendations'],
    4.8, 1234,
  ),
  mkAgent('tour-005', 'sa-foodie-guide', 'SA Foodie Intelligence', 'Tourism', 'pro', 'UtensilsCrossed',
    'Curated San Antonio food tour planning with Tex-Mex, BBQ, and James Beard restaurant discovery.',
    ['Restaurant curation', 'Reservation booking', 'Food tour planning', 'Chef events'],
    4.9, 1567,
  ),
  mkAgent('tour-006', 'sa-sports-guide', 'SA Sports & Entertainment', 'Tourism', 'pro', 'Trophy',
    'Spurs, San Antonio FC, Missions baseball \u2014 tickets, parking, and game-day planning.',
    ['Ticket booking', 'Parking guidance', 'Pre-game dining', 'Schedule alerts'],
    4.7, 876,
  ),
  mkAgent('tour-007', 'sa-art-culture', 'SA Arts & Culture Explorer', 'Tourism', 'pro', 'Palette',
    'McNay Art Museum, Witte Museum, and SA cultural district discovery with exhibit scheduling.',
    ['Exhibit discovery', 'Ticket booking', 'Artist info', 'Cultural events'],
    4.6, 456,
  ),
  mkAgent('tour-008', 'sa-day-trips', 'TX Hill Country Day Trips', 'Tourism', 'pro', 'Mountain',
    'Curated day trip itineraries from San Antonio to Fredericksburg, Wimberley, New Braunfels, and Bandera.',
    ['Route planning', 'Activity booking', 'Winery tours', 'State park access'],
    4.8, 789,
  ),
  mkAgent('tour-009', 'sa-convention-planner', 'Convention Center Planner', 'Tourism', 'pro', 'Building2',
    'Henry B. Gonz\u00e1lez Convention Center event planning, vendor coordination, and attendee logistics.',
    ['Venue booking', 'Vendor matching', 'Attendee coordination', 'A/V support'],
    4.5, 234,
  ),
  mkAgent('tour-010', 'sa-family-adventure', 'SA Family Adventure Planner', 'Tourism', 'pro', 'Smile',
    'SeaWorld, Six Flags, Natural Bridge Caverns \u2014 family itinerary planning with crowd forecasting.',
    ['Attraction booking', 'Crowd forecasting', 'Dining planning', 'Budget optimization'],
    4.7, 1123,
  ),

  // ═══ CONNECT-360 / SmartSA (10) ═══
  mkAgent('c360-001', 'connect-360-newcomer-onboarding', 'Connect-360 Newcomer Onboarding', 'Connect360', 'pro', 'UserPlus',
    'One-stop relocation concierge for newcomers moving to San Antonio — utilities, schools, neighborhoods, voter registration.',
    ['Relocation checklist', 'Utility signup', 'School finder', 'Neighborhood guide'],
    4.7, 234,
    'Guides new residents through the entire relocation process — setting up SAWS water, CPS Energy, finding schools, understanding neighborhoods, registering to vote, and discovering local services.',
  ),
  mkAgent('c360-002', 'saws-water-advisor', 'SAWS Water Advisor', 'Connect360', 'pro', 'Droplets',
    'SAWS water usage analysis, drought stage alerts, conservation rebates, and billing assistance.',
    ['Usage analysis', 'Drought alerts', 'Conservation rebates', 'Billing help'],
    4.5, 189,
  ),
  mkAgent('c360-003', 'unified-utility-coordinator', 'Unified Utility Coordinator', 'Connect360', 'pro', 'Plug',
    'Coordinate CPS Energy + SAWS + internet setup for new residents — one agent, all utilities.',
    ['Multi-utility signup', 'Cost estimation', 'Bundle deals', 'Move-in scheduling'],
    4.6, 156,
  ),
  mkAgent('c360-004', 'sa-k12-school-finder', 'SA K-12 School Finder', 'Connect360', 'pro', 'School',
    'Compare San Antonio ISD, Northside ISD, North East ISD, and charter schools by address, ratings, and programs.',
    ['School comparison', 'Enrollment guidance', 'Program search', 'District mapping'],
    4.8, 312,
  ),
  mkAgent('c360-005', 'sa-neighborhood-scout', 'SA Neighborhood Scout', 'Connect360', 'pro', 'Map',
    'Neighborhood comparison tool — housing costs, walkability, crime stats, school ratings, and commute times.',
    ['Cost analysis', 'Safety scores', 'Commute calculator', 'Amenity mapping'],
    4.7, 267,
  ),
  mkAgent('c360-006', 'opportunity-home-navigator', 'Opportunity Home Navigator', 'Connect360', 'pro', 'Home',
    'Section 8, affordable housing waitlists, and Opportunity Home SA program navigation and application assistance.',
    ['Eligibility check', 'Waitlist status', 'Application help', 'Housing search'],
    4.6, 198,
  ),
  mkAgent('c360-007', 'edwards-aquifer-monitor', 'Edwards Aquifer Monitor', 'Connect360', 'pro', 'Waves',
    'Real-time Edwards Aquifer level tracking, drought stage alerts, and water conservation rebate finder.',
    ['Aquifer levels', 'Drought stages', 'Rebate finder', 'Conservation tips'],
    4.4, 143,
  ),
  mkAgent('c360-008', 'sa-river-authority-agent', 'SA River Authority Agent', 'Connect360', 'pro', 'Anchor',
    'San Antonio River Authority flood alerts, creek monitoring, and floodplain lookup for property owners.',
    ['Flood alerts', 'Creek monitoring', 'Floodplain lookup', 'Permit guidance'],
    4.3, 112,
  ),
  mkAgent('c360-009', 'bexar-property-tax-advisor', 'Bexar Property Tax Advisor', 'Connect360', 'pro', 'Calculator',
    'Bexar County property tax estimation, homestead exemption filing, and BCAD protest assistance.',
    ['Tax estimation', 'Exemption filing', 'Protest guidance', 'Rate comparison'],
    4.7, 345,
    undefined, 'beta',
  ),
  mkAgent('c360-010', 'sa-voter-registration-agent', 'SA Voter Registration Agent', 'Connect360', 'pro', 'CheckSquare',
    'Voter registration status check, polling location finder, sample ballot preview, and election date reminders.',
    ['Registration check', 'Polling locator', 'Ballot preview', 'Election reminders'],
    4.8, 289,
    undefined, 'beta',
  ),
]

// ── Pricing Plans ────────────────────────────────────────────
export const SA_PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: '$49',
    priceNote: '/month',
    tagline: 'For individuals and small teams getting started with AI-powered SA intelligence.',
    agentCount: 70,
    features: [
      'All 70 SA agents',
      '1,000 requests per month',
      'Real-time SA data connections',
      'Browser-based access',
      'Email support',
      'Privacy-first design',
    ],
    description: null,
    monthly_price: 4900,
    annual_price: 47000,
    agent_tier: 'PRO',
    max_agents: 70,
    tokens_per_month: 50000,
    highlighted: false,
  },
  {
    id: 'growth',
    name: 'Growth',
    price: '$149',
    priceNote: '/month',
    tagline: 'For growing businesses that need full agent access, team collaboration, and analytics.',
    agentCount: 70,
    highlight: true,
    badge: 'Recommended',
    features: [
      'All 70 agents unlocked',
      '10,000 requests per month',
      'Priority data refresh cadence',
      'Team seats (up to 5 users)',
      'Priority email and chat support',
      'Usage analytics dashboard',
    ],
    description: null,
    monthly_price: 14900,
    annual_price: 143000,
    agent_tier: 'PRO',
    max_agents: 70,
    tokens_per_month: 1000000,
    highlighted: true,
  },
  {
    id: 'partner',
    name: 'Partner',
    price: '$499',
    priceNote: '/month',
    tagline: 'For organizations that need enterprise-grade scale, security, and dedicated support.',
    agentCount: 'unlimited',
    features: [
      'All 70 agents, unlimited seats',
      'Unlimited requests',
      'Dedicated account manager',
      'SSO / SAML authentication',
      'Custom data integrations',
      'SLA-backed uptime guarantee',
    ],
    description: null,
    monthly_price: 49900,
    annual_price: 479000,
    agent_tier: 'ENTERPRISE',
    max_agents: -1,
    tokens_per_month: -1,
    highlighted: false,
  },
]

// ── Category Metadata ────────────────────────────────────────
export const SA_CATEGORIES: { id: AgentCategory; label: string; description: string; icon: string; color: string; count: number }[] = [
  { id: 'Civic', label: 'Civic', description: 'City services, permits, elections, transit', icon: 'Building2', color: '#1e90ff', count: 10 },
  { id: 'Business', label: 'Business', description: 'Licensing, market intel, HR, tax', icon: 'Briefcase', color: '#00e5a0', count: 20 },
  { id: 'Military', label: 'Military', description: 'JBSA benefits, VA claims, veteran services', icon: 'Shield', color: '#ffb830', count: 10 },
  { id: 'Healthcare', label: 'Healthcare', description: 'Care navigation, insurance, prescriptions', icon: 'Heart', color: '#ff6b8a', count: 10 },
  { id: 'Tourism', label: 'Tourism', description: 'Riverwalk, Alamo, events, Hill Country', icon: 'MapPin', color: '#a78bfa', count: 10 },
  { id: 'Connect360', label: 'Connect-360', description: 'Cross-domain interoperability and SmartSA', icon: 'Globe', color: '#1e3a5f', count: 10 },
]
