import Link from 'next/link'

export default function AIDisclaimerPage() {
  return (
    <div className="min-h-screen bg-white pt-24 lg:pt-32 pb-20">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Disclaimer</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: May 14, 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-sm text-gray-600 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. Nature of AI Agents</h2>
            <p>
              The AI agents available on the SA Agent Marketplace are designed to provide
              informational assistance only. Agent responses are generated by artificial intelligence
              models and do not constitute professional advice of any kind. Agents are tools intended
              to support your research and decision-making, not replace qualified human expertise.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. No Guarantee of Accuracy</h2>
            <p>
              AI-generated content may contain errors, inaccuracies, or outdated information. While
              we strive to provide high-quality agent responses, artificial intelligence can and does
              make mistakes. You should independently verify any information, data, or recommendations
              provided by an agent before acting on them.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. Not Legal, Medical, or Financial Advice</h2>
            <p>
              Agent outputs do not constitute legal, medical, financial, tax, or any other form of
              licensed professional advice. Do not rely on agent responses as a substitute for
              consultation with a qualified attorney, physician, financial advisor, or other
              professional. Always seek appropriate professional counsel for matters requiring
              licensed expertise.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Data Sources</h2>
            <p>
              Our agents are trained on publicly available San Antonio-area data, including civic
              records, business directories, tourism information, military installation guides, and
              healthcare resources. This data may be incomplete, outdated, or may not reflect the
              most current conditions. We make no representation that agent knowledge is
              comprehensive or current.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Human Oversight Recommended</h2>
            <p>
              We strongly recommend that all agent outputs be reviewed by a qualified human before
              being used in any consequential decision. AI agents are best used as a starting point
              for research, not as a final authority. Critical decisions should always involve human
              judgment and verification.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Limitation of Liability</h2>
            <p>
              AI Cowboys, Inc. and the SA Agent Marketplace are not liable for any damages, losses,
              or consequences arising from reliance on AI-generated content. By using our agents,
              you acknowledge and accept that AI outputs are provided &ldquo;as is&rdquo; without
              warranties of accuracy, completeness, or fitness for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Contact</h2>
            <p>
              For questions about this disclaimer, contact us at{' '}
              <a href="mailto:legal@aicowboys.com" className="text-navy-700 hover:text-navy-950 underline underline-offset-2">
                legal@aicowboys.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-gray-100">
          <Link href="/" className="text-sm text-navy-700 hover:text-navy-950">
            &larr; Back to home
          </Link>
        </div>
      </div>
    </div>
  )
}
